export const VIEW_ALIAS_MAP = {
  thunderclaw: 'dashboard',
  main: 'dashboard',
  ai: 'dashboard',
  chat: 'dashboard',
  xline: 'kline',
  '虾线': 'kline',
  chart: 'kline',
  xstrategy: 'backtest',
  '虾策': 'backtest',
  strategy: 'backtest',
  xsea: 'xsea',
  '虾海': 'xsea',
  community: 'xsea',
  xbrain: 'xbrain',
  '虾脑': 'xbrain',
  brain: 'xbrain',
  config: 'xbrain',
  '配置': 'xbrain',
};
